### ISSUE TITLE
Upload Excel files to Power BI Report Server

### ISSUE THREAD

**Issue by bibe74** [ClaudioESSilva/SQLServer-PowerShell#2]
Although it's possible to upload Excel files to a PBIRS folder using Write-RsCatalogItem, the uploaded file gets recognized as a "Resource" instead of an "Excel workbook", as the same file appears to be catalogued when uploaded manually via the PBIRS web pages.

It would be nice to have the file(s) listed under the correct type.

**Comment by ClaudioESSilva** [comment]
Hi @bibe74, if you still have this issue, please open an issue on the official [ReportingServicesTools](https://github.com/microsoft/ReportingServicesTools) GitHub repository.

Thank you.
